### ISSUE TITLE
eslint-plugin-vue compatibility

### ISSUE THREAD

**Issue by kailniris** [Prettyhtml/prettyhtml#100]
## 🚀 Feature Proposal

There should be options to honor eslint-plugin-vue rules. According to the description this tool is opinionated so instead of [tweaking eslint rules](https://github.com/Prettyhtml/prettyhtml/issues/80) to be compatible with this formatter the tool should honor the plugin:vue/recommended rules by default or with options if this formatter wants to support vue files.

## Motivation

Vetur uses this html formatter by defeult in VSCode. Currently there is no tool for properly formatting vue file templates in VSCode if eslint-plugin-vue is used in the project.

## Example

I found the following two rules to be incompatible with the formatter.
[vue/singleline-html-element-content-newline](https://vuejs.github.io/eslint-plugin-vue/rules/singleline-html-element-content-newline.html)
[vue/html-closing-bracket-spacing](https://vuejs.github.io/eslint-plugin-vue/rules/html-closing-bracket-spacing.html)

## Vote

If you agree with my proposal vote with a 👍

**Comment by StarpTech** [comment]
Hi @kailniris thank you for your proposal. Please have in mind that prettyhtml wasn't made for vue only but I will accept any proposal which makes the output more readable and consistent.

1. [vue/singleline-html-element-content-newline](vue/singleline-html-element-content-newline) I don't understand this rule. It will add extra newlines where it's not neccessary.

2. [vue/html-closing-bracket-spacing](https://vuejs.github.io/eslint-plugin-vue/rules/html-closing-bracket-spacing.html) This is controversial and I don't see a benefit.

You can disable both rules in your eslint config and you're fine. If you have good real world examples of both rules please show me.

**Comment by kailniris** [comment]
In my opinion both rules serve readability but there is no point going into a tab vs space debate here.
Its possible to tweak eslint rules the match the formatter but I think its a really bad practice.
There is a centralized rule set and I think everybody should stick to it to maintain style consistency between projects. So if every tool would require just a little bit of tweaking to the different direction then there is no point of the rule set. For an example its a nightmare to setup airbnb-base and prettier together plus have a code formatter which outputs the same format as eslint --fix.
The reason I opened this issue because I have been working with vue in the past years and there is not a single html formatting tool for VSCode which works with vue files and honor eslint-plugin-vue rules. Vetur adapted this tool and it seems this formatter stands closest eslint-plugin-vue ruleset.

**Comment by StarpTech** [comment]
Hi @kailniris as I mentioned earlier prettyhtml wasn't built for vue only. The fact that some rules aren't 100% compatible with the default settings of an external package is no reason for me to change our rules. If you want to change something show us the clear benefit, both of your proposed rules are just a matter of taste.

**Comment by StarpTech** [comment]
> However there are already vue specific features, isn't it possible to add additional rules for vue files only?

This shows only the none HTML5 capabilities in order to support a broad range of frameworks.
Adding framework specific rules would collide with the goal of this project.
