### ISSUE TITLE
How to make '>' not a single line

### ISSUE THREAD

**Issue by HannibalKcc** [Prettyhtml/prettyhtml#107]
**ide:** VSCODE

**extention:** vetur

**setting.json:**
```
"vetur.format.defaultFormatterOptions": {
  "prettyhtml": {
    "printWidth": 120, // No line exceeds 100 characters
  }
}
```

source:
```
<el-tree ref="tree" show-checkbox :data="treeData" :default-expanded-keys="[1]" node-key="id"  :props="{ children: 'subList', label: 'name' }">{{someData}}</el-tree>
```

after format:
```
<el-tree
  ref="tree"
  show-checkbox
  :data="treeData"
  :default-expanded-keys="[1]"
  node-key="id"
  :props="{ children: 'subList', label: 'name' }"
  >{{someData}}</el-tree>
```

i hope get:
```
<el-tree
  ref="tree"
  show-checkbox
  :data="treeData"
  :default-expanded-keys="[1]"
  node-key="id"
  :props="{ children: 'subList', label: 'name' }"
  >
  {{someData}}
</el-tree>
```

thank you

**Comment by StarpTech** [comment]
Hi @HannibalKcc this is intentionally. A single node/expression is never wrapped on a new line.

**Comment by GodofHope** [comment]
but it is conflict with [singleline-html-element-content-newline](https://vuejs.github.io/eslint-plugin-vue/rules/singleline-html-element-content-newline.html), which is on in `plugin:vue/strongly-recommended` [link](https://vuejs.github.io/eslint-plugin-vue/rules/#priority-b-strongly-recommended-improving-readability)

**Comment by 7iomka** [comment]
> singleline-html-element-content-newline
@Mister-Hope , you found any solution? I have exact issue with this :(

**Comment by Mister-Hope** [comment]
nope, I had suggest the vetur team to change another formatter, since prettyhtml's author wasn't willing to help and add this feature.

**Comment by Mister-Hope** [comment]
But I have to say that only vue users will met this problem since single text content really shouldn't be wrapped.

**Comment by rcheung9** [comment]
@Mister-Hope Too bad this issue isn't fixed.  This should not be closed.

**Comment by Mister-Hope** [comment]
I agreed, but the author insisted his opinion.

**Comment by StarpTech** [comment]
@Mister-Hope just to clarify: This project isn't for vuejs only. I created it due to the missing HTML support in prettyhtml. Today, prettyhtml has great support and the power to maintain it. The core principle of this formatter is to stick with rules which are reasonable in terms of readability and shouldn't be controlled by a style guide like `eslint-plugin-vue`.

I'm looking for new maintainers. If you have a strong interest to support this project feel free to contact me.
