### ISSUE TITLE
.prettyhtmlrc

### ISSUE THREAD

**Issue by lucaperret** [Prettyhtml/prettyhtml#110]
## 🚀 Feature Proposal

As [prettier do](https://prettier.io/docs/en/configuration.html), use [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to get the prettyhtml configuration from the working directory.

## Motivation

I want to extend prettyhtml from the local project, [not from the Vetur VSCode extension configuration](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/htmlFormat.ts#L65).

## Example

.prettyhtmlrc
```json
{
    "wrapAttributes": true
}
```

## Vote

If you agree with my proposal vote with a 👍

**Comment by StarpTech** [comment]
Hi @lucaperret would you like to send a pr?
