### ISSUE TITLE
prettyhtml will remove auto close slash

### ISSUE THREAD

**Issue by qiu8310** [Prettyhtml/prettyhtml#112]
### Please note that this issue tracker is not a help form and this issue will be closed.

Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/Prettyhtml/Lobby) and ask any questions you have or mention any problems you've had getting started with prettyhtml.

```bash
echo "<input />" | ./node_modules/.bin/prettyhtml --stdin
```

will output

```html
<input>
```

How can I get `<input />` instead?

**Comment by vm0100** [comment]
I also have this problem.   <image></image> to  <image>

**Comment by gaetansenn** [comment]
Me too ! Can we add an option to this ?

**Comment by StarpTech** [comment]
Hi @qiu8310 this is expected behaviour because the `input` node is a void element and doesn't need to be closed per spec.
