### ISSUE TITLE
Set ">" after the last attributes configurable

### ISSUE THREAD

**Issue by kazehaiya** [Prettyhtml/prettyhtml#114]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

Print width: 40

```
// Origin Code
<ul class="classA classB classC" data-id="idA idB">
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>

// Current Style
<ul
  class="classA classB classC"
  data-id="idA idB"
  >  // new line
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>

// Better Style(I think)
<ul
  class="classA classB classC"
  data-id="idA idB"> // no new line
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>
```

## Motivation
shink code in editor(Ignore the whitespace problem):

```
// Current Style
<ul ...
>...
</ul>

// Better Style
<ul ...
</ul>
```

The methods before I should click twice and the second one looks more simple.

I see that plugin `js-beauty` has confugurable attribute `end_with_newline` can control the ">", but the wrap rule is not good as `prettyhtml`. So if the ">" can be configurable, I think that's not bad~ 

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

## Vote

If you agree with my proposal vote with a 👍

**Comment by lqzhgood** [comment]
to more new line~
I think this idea is great.
