### ISSUE TITLE
No unwrap after '>'

### ISSUE THREAD

**Issue by Mister-Hope** [Prettyhtml/prettyhtml#115]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

## Vote

If you agree with my proposal vote with a 👍

Sorry I am not a navtive English speaker, so forgive me to write like this way.

Vetur contain this lib as it's default html fixer. But , when I use [plugin:vue/strongly-recommended](https://vuejs.github.io/eslint-plugin-vue/rules/#priority-b-strongly-recommended-improving-readability), it turns on the rule [singleline-html-element-content-newline](https://vuejs.github.io/eslint-plugin-vue/rules/singleline-html-element-content-newline.html). Witch is conflict with this tools formatting method.

I wonder if you can make a new option for it.

**Comment by StarpTech** [comment]
Please provide a proper issue description.

**Comment by GodofHope** [comment]
Vetur contain this lib as it's default html fixer. But , when I use plugin:vue/strongly-recommended, it turns on the rule singleline-html-element-content-newline. Witch is conflict with this tools formatting method.

**Comment by GodofHope** [comment]
https://vuejs.github.io/eslint-plugin-vue/rules/singleline-html-element-content-newline.html

**Comment by GodofHope** [comment]
This tool wrap method is conflict with the rule above
