### ISSUE TITLE
prettier/third-party.js

### ISSUE THREAD

**Issue by Hezhenguo** [Prettyhtml/prettyhtml#120]
hello .
Why did I start the ./node_modules/prettier/third-party.js not found at startup, but I have downloaded the package successfully in node_moules.

**Comment by StarpTech** [comment]
Hello @Hezhenguo this doesn't look like a prettyhtml issue. Try to remove your node_modules and install them in a fresh state. If this doesn't help please open a new issue with a fully reproducible example.
