### ISSUE TITLE
ParseError: Void elements do not have end tags "image"

### ISSUE THREAD

**Issue by SilenceAdam** [Prettyhtml/prettyhtml#133]
## Info

  * Platform: macOS
  * Vetur version: 0.22.2
  * VS Code version: 1.37.1

## Problem

weex image component ,Formatting failed:Void elements do not have end tags "image"

## Reproducible Case

[![image](https://user-images.githubusercontent.com/13724148/64234243-78923500-cf28-11e9-8656-be5c44fa8145.png)](https://user-images.githubusercontent.com/13724148/64234243-78923500-cf28-11e9-8656-be5c44fa8145.png)

weex image component has end tags "image", but vetur think is error

**Comment by StarpTech** [comment]
Image is a self-closing tag according HTML. We don't support weex special syntax.

**Comment by StarpTech** [comment]
Feel free to investigate. I will try to help.

**Comment by shenchaoran** [comment]
Is there any progress, I have the same question
