### ISSUE TITLE
Security Issue - outdated meow package

### ISSUE THREAD

**Issue by Heartnett** [Prettyhtml/prettyhtml#143]
## 🐛 Bug Report

meow@5.0.0 uses trim-newlines@2.0.0 which has **Regular Expression Denial of Service** vulnerability.

## To Reproduce

`npm audit`

## Expected behavior

**No security vulnerabilities.**

## Context

- [ ] Angular
- [ ] Svelte
- [ ] Vue
- [ ] Riot
- [ ] HTML5 only

## Your Environment

- Prettyhtml version: **0.10.0**
- NodeJs version: N/A
- Environment name and version: N/A
- Operating System and version: N/A

**Comment by StarpTech** [comment]
Hi @Heartnett, this project is no longer maintained but I'd accept a PR if it is important for the community. I recommend to switch to prettier.

**Comment by Heartnett** [comment]
@StarpTech I dont use this project directly, but noted.

**Comment by Heartnett** [comment]
Maybe update the readme file to indicate that the project is no longer maintained?
