### ISSUE TITLE
Tabs and spaces are mixed when `use-tabs: true`

### ISSUE THREAD

**Issue by koca** [Prettyhtml/prettyhtml#31]
Hi, first of all thank you for the lib 👍

### Issue

When I configured prettyhtml to `useTabs` it indents using tabs except for the HTML attributes. Attributes indented using spaces. Which I guess should be indented using tabs. See the example below.

### Example

Ascii chars:

`·` &nbsp;Represents a space char

`→` &nbsp;Represents a tab char

Options:

```js
{
  useTabs: true,
  tabWidth: 2,
  printWidth: 80
}
```

Input:

```html
<div class="test">
··<prism-editor
····class="my-editor"
····:code="code"
····@change="changeCode"
····language="html"
··/>
</div>
```

Expected Output:
```html
<div class="test">
→   <prism-editor
→   →   class="my-editor"
→   →   :code="code"
→   →   @change="changeCode"
→   →   language="html"
→   />
</div>
```

Got: 
```html
<div class="test">
→   <prism-editor
→   ··class="my-editor"
→   ··:code="code"
→   ··@change="changeCode"
→   ··language="html"
→   />
</div>
```

you can also test it on [prettyhtml.netlify.com](https://prettyhtml.netlify.com)

- Click `VUE` example button 
- Click the `Use Tabs` option on the left
- Click `Run` button on the top right

You should see that attributes are indented using spaces not with tabs.

**Comment by StarpTech** [comment]
Hi @koca,
thank you for the bug report. I will investigate.
I like the prettyhtml 😄 great work! It would be great if you could host the project under the prettyhtml organisation. I can add you as a contributor?

**Comment by koca** [comment]
Thanks! Sure, let's do it :) where do we start?

**Comment by StarpTech** [comment]
Great! I added you as a member. You can move your project to prettyhtml org in the repo settings.

**Comment by koca** [comment]
Done! ^^

**Comment by StarpTech** [comment]
Welcome! 😄
