### ISSUE TITLE
minify-whitespace pkg is missing the `list.json` file

### ISSUE THREAD

**Issue by koca** [Prettyhtml/prettyhtml#41]
Hey! 

`Error: Cannot find module './list.json' from '@starptech/rehype-minify-whitespace'`

i'm getting this error when browserifying the prettyhtml. 
I guess you forgot to add `list.json` to package.json `files` section ?

**Comment by StarpTech** [comment]
You're right I will provide a fix in a minute.

**Comment by StarpTech** [comment]
Fixed in prettyhtml@0.2.1
