### ISSUE TITLE
improperly closed textarea element unexpectedly slurps following content 

### ISSUE THREAD

**Issue by maeldur** [Prettyhtml/prettyhtml#44]
## 🐛 Bug Report

Improper closing of <textarea> slurps up the rest of the content in the file (as opposed to adding a </textarea> tag and proceeding. 

## To Reproduce

Steps to reproduce the behavior: https://repl.it/repls/OnlyShabbyCgi

Paste your markup here:

```html
<!doctype html>
<html class="no-js" lang="">
  <body>
    <p>Hello</p>
    <textarea />
    <p>World</p>
  </body>
</html>
```
creates
```html
<!doctype html>
<html class="no-js" lang="">
<body>
  <p>Hello</p>
  <textarea/>
</body>
</html>
```

and

```html
<!doctype html>
<html class="no-js" lang="">
  <body>
    <p>Hello</p>
    <textarea>
    <p>World</p>
  </body>
</html>
```
produces
```html
<!doctype html>
<html class="no-js" lang="">
<body>
  <p>Hello</p>
  <textarea></textarea>
</body>
</html>
```
## Expected behavior

keep the textarea element, close it, and keep following content, as browsers generally behave

Paste the results here:

```html
<!doctype html>
<html class="no-js" lang="">
<body>
  <p>Hello</p>
  <textarea></textarea>
  <p>World</p>
</body>
</html>
```

## Context

- [x] HTML5 only

## Your Environment

- Prettyhtml version: 0.1.5
- NodeJs version: 9.7.1
- Environment name and version: repl.it
- Operating System and version: linux

**Comment by StarpTech** [comment]
Hi @maeldur thank you for the report. Your examples represent invalid HTML. Prettyhtml wasn't designed to be 100% HTML5 spec compliant and failure tolerant. In practice, you will use a framework like Angular or Vue which will warn you about such mistakes but I agree since we transform it silently we should warn about it. The errors are already collected so it should be easy to expose them.

If you use the prettyhtml cli such errors are already reported!

```
prettyhtml .\test.html

test.html
  5:3-5:12  warning  Only void and foreign elements can be self closed "textarea" ("
<body>
  <p>Hello</p>
   [ERROR ->]<textarea/>
</body>
</html>
")  ParseError
       8:1  warning  Unexpected character "EOF" ("
   <textarea/>
</body>
</html>
[ERROR ->]")                                    ParseError

‼ 2 warnings
```

**Comment by StarpTech** [comment]
Closed in https://github.com/Prettyhtml/prettyhtml/releases/tag/v0.3.0

**Comment by octref** [comment]
IMO, `Unexpected character "EOF"` is not a suggestive error message for unclosed elements...

**Comment by StarpTech** [comment]
@octref https://stackoverflow.com/questions/38903038/unexpected-character-eof-do-you-have-an-unescaped-in-your-template-use

**Comment by octref** [comment]
What I can do is to surface the line/column numbers from prettyhtml, so you could see where the error is in the editor. The error is a lexer error and I think you should be able to improve the error message by identifying the code path in the lexer and add a nicer error message over there.

**Comment by casey6** [comment]
> In practice, you will use a framework like Angular or Vue which will warn you about such mistakes but I agree since we transform it silently we should warn about it. 

I think it's worth mentioning that in the Vue ecosystem this is _not_ considered a mistake (despite technically being invalid markup). In fact it's the recommended way to write code in single file components. All other native html elements that I've tested seem to work fine with prettyhtml (`<div/>`, `<span/>`, `<header/>`, etc) with the exception of `<textarea/>`.

https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md

**Comment by StarpTech** [comment]
> All other native html elements that I've tested seem to work fine with prettyhtml (<div/>, <span/>, <header/>, etc) with the exception of <textarea/>.

Did you check it with the latest version? Self-closing known HTML elements are invalid. There is a list of valid [void elements](https://www.w3.org/TR/html5/syntax.html#void-elements) You only self-close custom elements.

**Comment by StarpTech** [comment]
In the version of prettyhtml we will throw errors and warnings. Checkout https://prettyhtml.netlify.com/

**Comment by casey6** [comment]
Ah, yep it looks like those other elements with throw errors now.

I'll reiterate that this conflicts with conventions in the Vue ecosystem. Obviously it's your call on whether that's important enough to reconsider the approach here. It might not be. But it's a bit unfortunate because it seemed like this formatter filled a big hole in the developer experience when working with Vue.

**Comment by StarpTech** [comment]
Hi @casey6 I'm open to any change. Feel free to make a proposal.

**Comment by casey6** [comment]
My suggestion would be to allow self-closing non-void native html elements. So `<img />` would be transformed to `<img>`, while `<div />` would be transformed to `<div/>` and not throw an error. Basically the way it was working prior to `v0.3.0` but fix the weird behavior with `<textarea/>`.

**Input:**

```html
<template>
  <div>
    <p>Hello</p>
    <textarea />
    <p>World</p>
  </div>
</template>
```

**Output:**


```html
<template>
  <div>
    <p>Hello</p>
    <textarea/>
    <p>World</p>
  </div>
</template>
```

I'm coming from the perspective of using this on Vue projects, while also using the default `eslint-plugin-vue` configuration. If you're looking to make this a good default choice for Vue developers I think it would make sense to allow self-closing html elements. If that's not the goal then I can understand raising an error in those situations, as it's not valid html.

**Comment by StarpTech** [comment]
Please create the proposal in a separate issue.

**Comment by StarpTech** [comment]
@casey6 proposal is tracked here https://github.com/Prettyhtml/prettyhtml/issues/55

**Comment by StarpTech** [comment]
@casey6 your proposal was implemented with https://github.com/Prettyhtml/prettyhtml/pull/56
