### ISSUE TITLE
unwanted tbody tags being inserted

### ISSUE THREAD

**Issue by shasderias** [Prettyhtml/prettyhtml#46]
## 🐛 Bug Report
prettyhtml is inserting unwanted tbody tags when formatting a Vue template where the actual tbody tag will be inserted by a component.

In the example below, the draggable component will provide the tbody tag. However, prettyhtml adds its own tbody tag, leading to 2 tbody tags in the final output.

## To Reproduce
$ prettyhtml [filename]

Paste your markup here:
```html
<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>
  <draggable :element="'tbody'">
    <tr v-for="val in data"
      :key="val">
      <td></td>
    </tr>
  </draggable>
</table>
```

## Expected behavior
HTML is formatted with no tbody tag inserted, instead got:

```html
<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>
  <draggable :element="'tbody'">
    <tbody>
      <tr v-for="val in data" :key="val">
        <td></td>
      </tr>
    </tbody>
  </draggable>
</table>
```

## Context
- [ ] Angular
- [ ] Svelte
- [x] Vue
- [ ] Riot
- [ ] HTML5 only

## Your Environment
- Prettyhtml version:
@starptech/prettyhtml@0.2.2
- NodeJs version:
v8.9.1
- Environment name and version:
Not sure what to provide here.
- Operating System and version:
Microsoft Windows [Version 10.0.17134.112]

**Comment by StarpTech** [comment]
Hi @shasderias thank you for the bug report. The bug was fixed in #47

**Comment by StarpTech** [comment]
Fix with https://github.com/Prettyhtml/prettyhtml/releases/tag/v0.2.4

**Comment by shasderias** [comment]
Thank you for the quick fix!
