### ISSUE TITLE
HTML attributes being transformed even on custom components

### ISSUE THREAD

**Issue by rndmerle** [Prettyhtml/prettyhtml#50]
I've noticed HTML attributes being transformed.

`=""` added for value-attributes:
```
<base-flex wrap><base-text title>Title</base-text></base-flex>
// formatted to <base-flex wrap=""><base-text title="">Title</base-text></base-flex>
```

hyphen removed when this attribute without hyphen exists:
```
<base-list item-type="contact"><!-- --></base-list>
// formatted to <base-list itemtype="contact"><!-- --></base-list>
```

I can understand why I probably shouldn't even use global HTML attributes like itemtype or title on custom components, but should I really be prevented to use the wrap attributes on a custom component just because it's defined for <textarea>?

Thanks for your time.

**Comment by StarpTech** [comment]
Hi @rndmerle I'm trying to understand your issue. If you use known empty html attributes like `wrap` they are transformed with hyphen. According to your second issue that `item-type` is transformed to `itemtype` this was fixed in the latest [version](https://prettyhtml.netlify.com/).

**Comment by rndmerle** [comment]
Thanks for your answer, and good news for "itemtype"!

About "wrap" attribute and such I was just wondering why prettyhtml is adding an empty value to some attributes.
The more I think of it the more I see the logic actually.
That's just a bit annoying for custom components (I can't use `wrap` or `title` as boolean attributes), but it's not a big deal :)

Thank!

**Comment by StarpTech** [comment]
> That's just a bit annoying for custom components (I can't use wrap or title as boolean attributes), but it's not a big deal :)

I understand it but in that case, you shouldn't collide with public properties and as described before `wrap=""` is exactly the same as `wrap` so it should detected as true in your logic. Unset properties are `null`

**Comment by ScreamZ** [comment]
@StarpTech I'm using `vuetify` with vetur which is a completion extension for vsCode for vueJS.

I'm always using things like `<v-layout row wrap>` and this get converted to `<v-layout row wrap="">` is there any way to prevent this ? (confort)

Regards

**Comment by StarpTech** [comment]
@rndmerle @ScreamZ I opened a new issue for that https://github.com/Prettyhtml/prettyhtml/issues/53
