### ISSUE TITLE
When nesting single/double quote element attribute values, incorrect markup can be generated

### ISSUE THREAD

**Issue by maeldur** [Prettyhtml/prettyhtml#52]
## 🐛 Bug Report

When nesting single/double quote element attribute values, incorrect markup can be generated.  For example <div @click="onClick('div')"></div> and using single quotes, it becomes <div @click='onClick('div')'></div>

also vice versa with @click='onClick("div")' with double quotes, becomes @click="onClick("div")" 

## To Reproduce

https://repl.it/repls/OnlyShabbyCgi

Paste your markup here:

```html
<!doctype html>
<html class="no-js" lang="">
  <body>
    <p>Hello</p>
    <div @click='clicked("div")'></div>
    <p>World</p>
  </body>

</html>
```

## Expected behavior

I expect the nested quotes to be replaced with the valid quote type based on the outer quote type.  (single for double, double for single)

Paste the results here:

```html
<!doctype html>
<html class="no-js" lang="">
  <body>
    <p>Hello</p>
    <div @click="clicked('div')"></div>
    <p>World</p>
  </body>

</html>
```

## Context

- [ ] Angular
- [ ] Svelte
- [x] Vue
- [ ] Riot
- [ ] HTML5 only

## Your Environment

- Prettyhtml version: 0.3.3
- NodeJs version: 9.7.1
- Environment name and version: repl.it
- Operating System and version: repl.it

**Comment by maeldur** [comment]
oops, hit enter too early on the issue. filling out the body now.

**Comment by StarpTech** [comment]
Hi @maeldur thank you for the bug report. This is a well known behaviour and a limitation. The formatter doesn't escape or sanitize your content. You have to decide for one way.
