### ISSUE TITLE
<tbody> element added as <tr> parent

### ISSUE THREAD

**Issue by rndmerle** [Prettyhtml/prettyhtml#57]
## 🐛 Bug Report

If the parent of `<tr>` is not `<tbody>` then a `<tbody>` element is added.
But with custom components, prettyhtml can't see if the parent isn't providing the `<tbody>` element under the hood. And a double `<tbody>` is pretty bad.

## To Reproduce

```html
<custom-table-body>
  <tr></tr>
<custom-table-body>
```

## Expected result

```html
<custom-table-body>
  <tr></tr>
<custom-table-body>
```

## Actual result

```html
<custom-table-body>
  <tbody>
    <tr></tr>
  </tbody>
<custom-table-body>
```

## Context

- [ ] Angular
- [ ] Svelte
- [X] Vue
- [ ] Riot
- [ ] HTML5 only

## Your Environment

- Prettyhtml version: 0.3.3
- NodeJs version: 8.11.4
- Environment name and version: VSCode 1.28.2 / Vetur 0.13.0
- Operating System and version: MacOs Mojave

**Comment by rndmerle** [comment]
I've just seen https://github.com/Prettyhtml/prettyhtml/issues/46
not sure why it's still happening.

**Comment by StarpTech** [comment]
Hi @rndmerle thanks for the bug report. In your markup, you don't close any tag. When I format
```html

```

**Comment by StarpTech** [comment]
Vetur needs an update to 0.4.x

**Comment by rndmerle** [comment]
Sorry for the troubles. Actually the used version is older than 0.3.3.
I looked in package.json from Vetur extension to get the version but actually the latest release Vetur 0.13.0 is older than that :(
Works great with the prettyhtml client.

Sorry again.

**Comment by StarpTech** [comment]
No problem. Would you mind to create a PR to update vetur?

**Comment by rndmerle** [comment]
Well, it seems they update prettyhtml package pretty often. It's just that their release schedule is not as fast.
