### ISSUE TITLE
Base indentation inside <script> and <style>

### ISSUE THREAD

**Issue by rndmerle** [Prettyhtml/prettyhtml#59]
## 🚀 Feature Proposal

Prettier applied on a .vue file will remove the base indentation of <script> and <style> content:

Input:
```html
<script>
  console.log('Hello World!');
</script>
```

Output:
```html
<script>
console.log('Hello World!');
</script>
```
Not everyone is happy with this tho: https://github.com/prettier/prettier/issues/3888

Prettyhtml actually do the opposite:

Input:
```html
<script>
console.log('Hello World!');
</script>
```

Output:
```html
<script>
  console.log('Hello World!');
</script>
```

## Desired output

There are two solutions imo:
- Follow the current convention established by Vue guidelines and followed by Prettier: remove initial indentation on <script> and <style> content
- Be flexible and align the base indentation with the first line of the element. For instance:

Input:
```html
<script>
  console.log('Hello');
console.log('World!');
</script>
```
Output:
```html
<script>
  console.log('Hello');
  console.log('World!');
</script>
```

Input:
```html
<script>
console.log('Hello');
  console.log('World!');
</script>
```
Output:
```html
<script>
console.log('Hello');
console.log('World!');
</script>
```

## Motivation

Either respect the current Vue / Prettier convention, or respect the current initial base indentation.

**Comment by StarpTech** [comment]
I agree we should be consistent. Would you like to send a PR?

**Comment by StarpTech** [comment]
Could you reference to the vue guideline?

**Comment by rndmerle** [comment]
I'm a bit surprised it's not on the guidelines (https://vuejs.org/v2/style-guide/), it's just formatted this way on guidelines examples. It's probably enough to make prettier favor this style.
I can't test right now how it's formated on a regular html file.

Vetur Vscode extension has an option to indent script and style content (off by default).
I guess people format either way, unless they use Prettier client.

**Comment by rndmerle** [comment]
Interesting survey.
I think it's reasonable to let it this way actually.

People preferring to indent might find in Prettyhtml a good alternative to Prettier's client. Because I doubt they change this behavior.

And people preferring no indentation can just apply Prettier after Prettyhtml.

**Comment by pbastowski** [comment]
Hi guys

Can I assume by the `proposal` tag that this feature is going ahead?

In case it is, it says here how to do it: https://github.com/prettier/prettier/issues/3888#issuecomment-385960667

Also, is it likely to be implemented before Christmas 2018?

Thanks for creating the proposal. I thought I'd retire before I saw it happen 😄

**Comment by StarpTech** [comment]
Hi @pbastowski no problem. Did you give Prettyhtml a try?

**Comment by StarpTech** [comment]
I will close this issue for now. Feel free to reopen.

**Comment by pbastowski** [comment]
@StarpTech No, I haven't tried it yet. Sounds like something to do on the weekend.

**Comment by StarpTech** [comment]
@pbastowski I appreciate any feedback!

**Comment by xiaomingplus** [comment]
I think the intend should be use prettier config tabWidth. I will give you a pull request

```js
function indentPrettierOutput(formattedText, level) {
  let lines = formattedText.split(single)

  for (let i = 0; i < lines.length; i++) {
    if (lines[i].replace(/\s+/g, '').length) {
      lines[i] = repeat('  ', level) + lines[i]
    }
  }

  return lines.join(single)
}
```
