### ISSUE TITLE
Extra line added under comments containing "if"

### ISSUE THREAD

**Issue by bsaf** [Prettyhtml/prettyhtml#60]
## 🐛 Bug Report

A rogue extra line is being added under comments containing the word "if".

## To Reproduce

Steps to reproduce the behaviour:

```html
<!-- Brunch-->
<p>Brunch</p>
<!-- Gifts -->
<p>Gifts</p>
```

## Expected behaviour

Should output the same as the input.

## Actual behaviour

```html
<!-- Brunch-->
<p>Brunch</p>
<!-- Gifts -->

<p>Gifts</p>
```

## Context

Just plain HTML5.

**Comment by StarpTech** [comment]
Hi @bsaf thanks for the bug report. Would you like to send a PR?
The issue is [here](https://github.com/Prettyhtml/prettyhtml/blob/master/packages/prettyhtml-formatter/index.js#L370). We have to match for `\s[if` not for any if in the comment node.

**Comment by bsaf** [comment]
Will do! Will try and do this week. Thanks for the pointer to the code.
