### ISSUE TITLE
Formatter removes spaces around inline elements

### ISSUE THREAD

**Issue by thedamon** [Prettyhtml/prettyhtml#65]
## To Reproduce

```html
<p>I am writing to tell you that I am <em>extremely</em> excited about this new <a href="http://w3c.com">HTML</a> formatter. It promises to be <small>as far as I can tell</small> both <strong>flexible</strong> and <strong>resilient</strong> in the face of many new ways of writing <i>HTML</i>
```

## Current behaviour

```html
<p>I am writing to tell you that I am
  <em>extremely</em>excited about this new
  <a href="http://w3c.com">HTML</a>formatter. It promises to be
  <small>as far as I can tell</small>both
  <strong>flexible</strong>and
  <strong>resilient</strong>in the face of many new ways of writing
  <i>HTML</i>
</p>
```

## Expected behavior

Spaces around words should not be removed. The current behaviour breaks completely reasonable and common ways of writing HTML by forcing multiple words together. it should at the very least retain the space between the end of the tag and a new word not contained by a tag

## Context
Used the netlify site to create this example.

**Comment by StarpTech** [comment]
Hi @thedamon thanks for the report. Would you like to send a PR?
