### ISSUE TITLE
foramt image tag throw error

### ISSUE THREAD

**Issue by xiaomingplus** [Prettyhtml/prettyhtml#72]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/Prettyhtml/Lobby) and ask any questions you have or mention any problems you've had getting started with prettyhtml.

## 🐛 Bug Report

format a <image> tag, throw Error.

## To Reproduce

Config: Defaull config

Paste your markup here:

```html
<template>
    <div>
        <image src="http://google.com">
    </div>
</template>
```

## Expected behavior

Paste the results here:

```html
<template>
    <div>
        <image src="http://google.com" />
    </div>
</template>
```

## Context

  Vue or html

## Your Environment

- Prettyhtml version: @starptech/prettyhtml@0.8.2
- NodeJs version:8.12.0
- Environment name and version:
- Operating System and version: macos

**Comment by StarpTech** [comment]
Hi @xiaomingplus thanks for the report. Prettyhtml isn't responsible to fix your HTML it expect 100% valid HTML5 markup. The `image` tag has to be closed with a slash.

**Comment by xiaomingplus** [comment]
@StarpTech yes, but if I close the ```image``` with a slash,prettyhtml will remove the slash,and again run prettyhtml,it will throw a Error

**Comment by StarpTech** [comment]
@xiaomingplus oh I was confused by the name `image` I interpreted it as `img` 😄 This is an issue.

Have a look [here](https://www.w3.org/TR/html51/syntax.html#named-character-references) and search for `image`

The issue is that we don't interpret `image` tag as a valid void element. We just need to add the element [here](https://github.com/Prettyhtml/prettyhtml/blob/master/packages/webparser/src/html_tags.ts#L97). Would you like to create a PR?

**Comment by xiaomingplus** [comment]
I'll try,thank you!

**Comment by xiaomingplus** [comment]
input: 
 ```html
<template>
  <div>
    <image src="http://google.com" />
  </div>
</template>
```

output:

```html
<template>
  <div>
    <image src="http://google.com" />
  </div>
</template>

```


or,input:


```html
    <image src="http://google.com"></image>

```

output:

```html
   <image src="http://google.com"></image>
```

or ,input : 

```html
<image src="">
```

output:

```html
<image src="" />
```


but,I don't know how to do this.

**Comment by StarpTech** [comment]
I think we should treat it as a void element. It's a equals to the `img` according to the specs.
