### ISSUE TITLE
Put ">" after the last attribute when wrapping multiple attributes

### ISSUE THREAD

**Issue by lhajh** [Prettyhtml/prettyhtml#77]
## 🚀 Feature Proposal

For multiple attributes that extend beyond the printWidth, I would prefer this:

```html
<p
  class="class"
  title="title">
  <span
    class="class"
    title="title"
  >test</span>
</p>
```

not this:

```html
<p
  class="class"
  title="title"
>
  <span
    class="class"
    title="title"
  >test</span>
</p>
```

Although this is prettier than the one above, but indentation is a hassle, so can you add a configuration to choose between this two formatting options?

## Vote

If you agree with my proposal vote with a 👍

**Comment by StarpTech** [comment]
Hi @lhajh thank you for the proposal but doesn't include a comparison about pro and cons. The current rule was adopted by vue styleguide because it reduces whitespace it easy to understand when a tag begins.

**Comment by barnesheaton** [comment]
My argument would be that this would reduce the number of lines on especially large files. Super nice if you're already used to reading your templates in the proposed format anyways.
