### ISSUE TITLE
prettyhtml-quick with .vue files

### ISSUE THREAD

**Issue by my9074** [Prettyhtml/prettyhtml#81]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

I learned from `vetur` that it formats html via `prettyhtml`. So I am going through `prettyhtml-quick` to prepare the `template` for verifying the vue file in the `pre commit` stage. But I found that it does not verify the `vue` file.

I looked at the source code and found that [prettyhtml-quick, L30](https://github.com/Prettyhtml/prettyhtml/blob/master/packages/prettyhtml-quick/bin/cli.js#L30) is so implemented.

I am thinking about whether you can use `vetur` to implement detection of vue files.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

![image](https://user-images.githubusercontent.com/4555635/49505793-7b87c880-f8b7-11e8-9653-bdec3c5807bc.png)

## Vote

If you agree with my proposal vote with a 👍

**Comment by StarpTech** [comment]
Hi @my9074 thank you for the proposal. In the first instance prettyhtml has nothing to do with vetur it's just a consumer of this tool. Prettyhtml was build for web frameworks only without any convern to parse a specific file format e.g `.vue` etc. If you need a preprocessor you have to implement by yourself or create a feature-requests in vetur.
