### ISSUE TITLE
Script comment format error

### ISSUE THREAD

**Issue by xiaomingplus** [Prettyhtml/prettyhtml#83]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/Prettyhtml/Lobby) and ask any questions you have or mention any problems you've had getting started with prettyhtml.

## 🐛 Bug Report

Prettyhtml format comment add an intend every running format.

## To Reproduce

Paste your markup here:

```html
<script>
    /* test
    test */
</script>
```

## Expected behavior

I think prettyhtml should do nothing with  the comment,prettier also do nothing.

Paste the results here:

```html
<script>
    /* test
    test */
</script>
```

## Context

 [
Vue
## Your Environment

- Prettyhtml version: 0.8.7
- NodeJs version: 8.12
- Environment name and version:
- Operating System and version:

**Comment by StarpTech** [comment]
Hi @xiaomingplus thank you for the bug report but this is indeed the correct behaviour. We indent the code with the base indentation. This is an opinionated approach discussed in detail [here](https://github.com/Prettyhtml/prettyhtml/issues/59)

```js
<script>
    /* test
    test */
var a = "deded"
</script>
```
```js
<script>
  /* test
      test */
  var a = "deded";
</script>
```

**Comment by StarpTech** [comment]
@xiaomingplus thank you. I will investigate.

**Comment by StarpTech** [comment]
The issue was fixed in https://github.com/Prettyhtml/prettyhtml/releases/tag/v0.8.9
