### ISSUE TITLE
running CLI on file that doesn't exist will create an empty file

### ISSUE THREAD

**Issue by flurmbo** [Prettyhtml/prettyhtml#84]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/Prettyhtml/Lobby) and ask any questions you have or mention any problems you've had getting started with prettyhtml.

## 🐛 Bug Report

If I run the command `packages/prettyhtml/cli.js doesnotexist.html` from my terminal, I get the following error message:

```
doesnotexist.html
  1:1  error  No such file or directory

✖ 1 error
```

This is as expected, but when I look at the contents of the folder I now see a blank file titled doesnotexist.html. 

## To Reproduce

Steps to reproduce the behavior: Run the command packages/prettyhtml/cli.js doesnotexist.html from the terminal

Paste your markup here:

```html

```

## Expected behavior

A clear and concise description of what you expected to happen: Node will give an error message without creating a new file

Paste the results here:

```html

```

## Context

- [ ] Angular
- [ ] Svelte
- [ ] Vue
- [ ] Riot
- [ ] HTML5 only

## Your Environment

- Prettyhtml version: 0.8.6
- NodeJs version: 10.13.0
- Environment name and version:
- Operating System and version: Ubuntu 18.04.1

**Comment by StarpTech** [comment]
Issue was reported in https://github.com/unifiedjs/unified-engine/issues/34

**Comment by StarpTech** [comment]
Fixed with latest update of unified engine.
