### ISSUE TITLE
@starptech/rehype-minify-whitespace npm package is missing some files

### ISSUE THREAD

**Issue by xiaomingplus** [Prettyhtml/prettyhtml#92]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/Prettyhtml/Lobby) and ask any questions you have or mention any problems you've had getting started with prettyhtml.

## 🐛 Bug Report

I think 0.8.13 `@starptech/rehype-minify-whitespace` is missing some files, such `list.js`

## context

your can run : 

```shell
npm i @starptech/rehype-minify-whitespace
```

the `node_modules/@starptech/rehype-minify-whitespace ` didn't have `list.js`.

so `prettyhtml` crashed.

## Your Environment

- Prettyhtml version: 0.8.13
- NodeJs version:8.12
- Environment name and version:
- Operating System and version:

**Comment by StarpTech** [comment]
Thank you for the bug report. It will be fixed asap.

**Comment by StarpTech** [comment]
Fixed in v0.8.14
