### ISSUE TITLE
prettyhtml换行格式化

### ISSUE THREAD

**Issue by chenshipi** [Prettyhtml/prettyhtml#98]
如何将prettyhtml换行格式化设置成js-beautify-html的force-aligned效果？
列如超过100长度换行效果
<button @click="getDate"
            class="test-btn"
            style="border:1px solid #cccccc;"
            prop="ceshi"
            label="qunidayede"></button>
而不是下面这种
<button
      @click="getDate"
      class="test-btn"
      style="border:1px solid #cccccc;"
      prop="ceshi"
      label="qunidayede"
    ></button>

**Comment by StarpTech** [comment]
Hi @chenshipi please create an issue in English.
