### ISSUE TITLE
Wrap by attribute

### ISSUE THREAD

**Issue by magpiedigital** [Prettyhtml/prettyhtml#99]
## 🚀 Feature Proposal

It would be a great feature to be able to wrap by the attribute type. This way some of your attributes will stay on the first line, some will get moved onto a new line. As an added bonus, these would be ordered to your preference.

## Motivation

I find that just newlining by number of attributes makes the code inconsistent and more difficult to read. Personally, I like class attribute to always be on the same line as the tag name, and it would be nice if I could choose if id always wrapped. That would make it very clear to see which tags have ids, as an example.

## Example

`<Component class="component" v-for="(item, i) in items" :key="item.id" v-if="i === 0 || i === 1" :wordId="wordId" v-show="i === 0" data-data1="data" otherAttr="otherAttr"/>`

By supplying an array of objects with string/regex selectors like so in user options: 

```
[
  { selector: 'class', wraps: false },
  { selector: /data-.*/, wraps: false },
  { selector: 'v-for', wraps: true },
  { selector: /:key/, wraps: false },
  { selector: 'v-if', wraps: true },
  { selector: 'v-show', wraps: true },
  { selector: /:((?!key).)*/, wraps: true }
]
```

would become

    <Component class="component"  data-data1="data"
               v-for="(item, i) in items" :key="item.id" 
               v-if="i === 0 || i === 1" 
               v-show="i === 0" "
               :wordId="wordId" otherAttr="otherAttr"/>

N.B in this example I've ordered the attributes by the order of the provided array. That would be a great feature!

## Vote

If you agree with my proposal vote with a 👍

**Comment by StarpTech** [comment]
Hi @magpiedigital thank your for the proposal. Prettyhtml is very opinionated and I think there are a bunch of people who don't like it but it works great so far. It should be simple as possible and we follow the same option [philosophy](https://prettier.io/docs/en/option-philosophy.html) as prettier. Your proposal would introduce many changes and too much flexibility to force a specific style.
